# https://gist.github.com/mattbrailsford/95c6f42fd133aac8a971213346ef1a28
language: node_js
node_js:
  - lts/*

os:
  - linux
dist: focal

branches:
  only:
    - master

cache: yarn

script:
  - yarn lint
